### ISSUE TITLE
Java7 support

### ISSUE THREAD

**Issue by Dahie** [CTDP/rfDynHUD#1]
[Reported in our forum](http://forum.ctdp.net/viewtopic.php?f=230&t=65325&p=801476#p801476)

Summary:

rfDynHUD is not optimized for Java7 and may not work and may not compile. At the moment it requires JRE6-32bit and support for JRE7 is not yet given.

**Comment by prunn** [comment]
I had a look and it seems there are lots of references in the source of  jvm_connection.ccp to jre6
the java side looks ok for java7
unfortunately I don't have VS install to try that

**Comment by prunn** [comment]
...I faked a jre6 with jre7 files... works perfecty

change all the msvcr71.dll to msvcr100.dll
and the registry check (both should not exists)
SOFTWARE\JavaSoft\Java Runtime Environment\1.6
to
SOFTWARE\JavaSoft\Java Runtime Environment\1.7

ultimately maybe put a condition so it works on both version and the issue will be fixed

**Comment by Qudus** [comment]
The plugin is now perfectly compatible with Java 7. I'm sorry to post this so late here. A new release will follow soon.
